### PR TITLE
Restructure french translation to match main documentation

### PR DESCRIPTION
**Pull request by silopolis**
First shoot at trying to make french documentation good enough to be updated.
Please consider this as a PR for comment as this is quite new to me...

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Look like a step in the right direction.  I tested using docs/po/migrate-translation after modifying it to enable adoc migration and drop the non-french languages, and there are several issues left to fix before the migration will work, the first one being with docs/src/code/nml-messages_fr.adoc.

**Comment by smoe** [comment]
I am not exactly sure about what the "force-push" now means but the individual diffs all seem very nice.
@petterreinholdtsen , you please ping me when it is time for me to continue.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> I am not exactly sure about what the "force-push" now means but the
> individual diffs all seem very nice.
> @petterreinholdtsen , you please ping me when it is time for me to
> continue.

Assuming you are talking about working on the migration of the french
adoc files, please go ahead.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
Yes, but are you aware of https://github.com/petterreinholdtsen/linuxcnc/pulls and should I not branch of whatever you then merge?

**Comment by silopolis** [comment]
@smoe very glad my work looks clean.
About the force push, this may be due to a looong night fighting with my git skills and history, trying to finally make a clean PR! This finally ended with a force push to update my GH branch.

**Comment by petterreinholdtsen** [comment]
Had forgotten the change was a pull request for my branch.  Merged now.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Pull request merged**
